### ISSUE TITLE
Windows file path for .netrc

### ISSUE THREAD

**Issue by RichardScottOZ** [rmg55/CloudDAAC_Binders#2]
Tinkering with this for Brazil in my fork, haven't done anything systematic yet...

C:\User or something along those lines...plus appropriate commands to make files? Or.. get unix utilities to do this. :)

**Comment by rmg55** [comment]
@RichardScottOZ, I am unable to test on a windows system, but I *think* this code should work on both linux and windows - https://git.earthdata.nasa.gov/projects/LPDUR/repos/daac_data_download_python/browse/EarthdataLoginSetup.py.

Also see this tutorial - https://lpdaac.usgs.gov/resources/e-learning/getting-started-cloud-native-hls-data-python/#processhls

hope that helps

**Comment by RichardScottOZ** [comment]
Thanks, yes thanks, I think I have used that in the past, 

this was my first thought hack when I tried it out the other day

try:
        netrcDir = os.path.expanduser(r'C:\users)
        #netrcDir = os.path.expanduser("~/.netrc")
        netrc(netrcDir).authenticators(urs)[0]
        del netrcDir

That is definitely better and OS proof
